baseURL = "https://ellie-heidari.github.io/portfolio/"
languageCode = "en"
title = "Ellie Heidari — Embedded Software"
theme = "PaperMod"

[outputs]
  home = ["HTML","RSS","JSON"]

[pagination]
  pagerSize = 10

[minify]
  disableXML = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  lineNos = true
  guessSyntax = true

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  showtoc = true
  tocopen = false
  author = "Ellie Heidari"
  description = "Firmware • Drivers • RTOS • Bootloaders • Test"
  images = ["images/og.png"]

# leave menus/links as-is (no color settings here)

